url = 'https://Solxcero.github.io
baseURL = ''
languageCode = 'en-us'
theme = "paper"
title = 'Ahora'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  #twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'github.com/Solxcero'                 # github.com/YOUR_GITHUB_ID
  #instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  #linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
  #mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  #rss = true                                # show rss icon

  # home page profile
  avatar = 'rumbini98@gmail.com'                 # gravatar email or image url
  name = 'Sunyoung Lee'
  bio = 'Version 1.0.0'