url = 'https://Solxcero.github.io'
baseURL = ''
languageCode = 'en-us'
theme = "paper"
title = 'Ahora'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'Solxcero'                 # github.com/YOUR_GITHUB_ID

  # home page profile
  avatar = 'https://github.com/Solxcero/Solxcero.github.io/assets/99321739/4ccb5f75-725b-4360-b1d6-6b1c99072d56'                 # gravatar email or image url
  name = 'Sunyoung Lee'
  bio = 'Version 1.0.0'
  
# ------------------------------
 
  # needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true


[menu]

  [[menu.main]]
    identifier = "categories"
    name = "categories"
    url = "/categories/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"