url = 'https://Solxcero.github.io'
baseURL = ''
paginate = 5
languageCode = 'en-us'
theme = "paper"
title = '漸入佳境'

[params]
  # color style
  color = 'light'                           # linen, wheat, gray, light

  # header social icons
  github = 'Solxcero'                 # github.com/YOUR_GITHUB_ID

  # home page profile
  avatar = 'https://github.com/Solxcero/Solxcero.github.io/assets/99321739/4ccb5f75-725b-4360-b1d6-6b1c99072d56'                 # gravatar email or image url
  name = '덕후의 즐거운 인생'
  bio = '좋아하는 것만 하고 살면 얼마나 좋게요'
  math = true


# ------------------------------
 
  # needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      attribute = true # 블록과 인라인 태그 속성 활성화
    [markup.goldmark.renderer]
      unsafe = true  # HTML 태그를 허용하도록 설정
    [markup.goldmark.extensions]

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    #style = 'native'   #native
    tabWidth = 4

[menu]

 # [[menu.main]]
    #identifier = "about"
    #name = "About"
    #url = "/about/"
    #weight = 13

#  [[menu.main]]
#    identifier = "tags"
#    name = "Tag"
#    url = "/tags/"
#    weight = 13
    
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 13

#  [[menu.main]]
#    identifier = "archive"
#    name = "Archive"
#    url = "/archives/"
#    weight = 13

[taxonomies]
  category = "categories"
  tag = "tags"
#  series = "series"
 